### ISSUE TITLE
Queue Now button does not work

### ISSUE THREAD

**Issue by maletor** [resque/resque-scheduler#220]
Clicking the queue now button returns a 303 status and redirects to the overview page and the job remains in the delayed tab.

**Comment by nikitsaraf** [comment]
+1
I am facing the same issue. It just redirects to the overview on pressing the queue now button.
The Logs are exactly similar to @enricostano's Logs
```
Started POST "/resque/delayed/queue_now" for 127.0.0.1 at 2015-01-27 02:15:14 -0600
Started GET "/resque/overview" for 127.0.0.1 at 2015-01-27 02:15:14 -0600
Started GET "/resque/reset.css" for 127.0.0.1 at 2015-01-27 02:15:14 -0600
Started GET "/resque/ranger.js" for 127.0.0.1 at 2015-01-27 02:15:14 -0600
Started GET "/resque/style.css" for 127.0.0.1 at 2015-01-27 02:15:14 -0600
Started GET "/resque/jquery-1.3.2.min.js" for 127.0.0.1 at 2015-01-27 02:15:14 -0600
Started GET "/resque/jquery.relatize_date.js" for 127.0.0.1 at 2015-01-27 02:15:17 -0600
Started GET "/resque/poll.png" for 127.0.0.1 at 2015-01-27 02:15:17 -0600
```

**Comment by fcsonline** [comment]
I have been investigating a little bit more about this issue. The main problem is regarding a conflict between process locks. Usually the Resque webapp and the scheduler are running in different process ids. When you click *Queue now* button, the `enqueue_delayed_items_for_timestamp` is called in Resque webapp process. This function calls the master lock check and the acquire function is rejected because Resque scheduler process has the lock. 

```ruby
      # Enqueues all delayed jobs for a timestamp
      def enqueue_delayed_items_for_timestamp(timestamp)
        item = nil
        loop do
          handle_shutdown do
            # Continually check that it is still the master
            if master? # <- Here is the `Queue now` issue
              item = Resque.next_item_for_timestamp(timestamp)
              if item
                log "queuing #{item['class']} [delayed]"
                handle_errors { enqueue_from_config(item) }
              end
            end
          end
          # continue processing until there are no more ready items in this
          # timestamp
          break if item.nil?
        end
      end
```

This function is called when the time to execute a job has arrived too. We need a solution to differentiate them.

What do you think about to ignore the `master?` check in this function when is called from the `Queue now` button?

**Comment by bcaccinolo** [comment]
@fcsonline I have the same feeling as you. `master?` should be ignored when this function is called from the `Queue now` button.
