### ISSUE TITLE
Resilient lock does not react on timeout attribute changes

### ISSUE THREAD

**Issue by dirkbolte** [resque/resque-scheduler#299]
`Resque::Scheduler::Lock::Base` offers an interface to modify the timeout. I'm not sure whether this is meant to be a public interface, but it has an accessor.
When doing so, this is not reflected in the calls to redis as the timeout is part of the hashed script that is uploaded:

``` ruby
Resque::Scheduler.is_master? ; Resque.redis.ttl(Resque::Scheduler.send(:master_lock_key))
=> 180
Resque::Scheduler.master_lock.timeout = 120
Resque::Scheduler.is_master? ; Resque.redis.ttl(Resque::Scheduler.send(:master_lock_key))
=> 180
```

**Comment by dedleman** [comment]
Able to reproduce the issue with version 4.3.0 when another process is the master.
Open 2 different rails consoles and set timeout in one after making it the master via the master? method and notice the timeout "sticks". 
In the second rails console try to set the timeout but it will be to no avail due to the call to `if locked?` in  `Resilient` preventing the attribute from being updated. The result is when the other process is promoted the ttl will be set to 180. Wondering why the timeout= method does the call to `if locked?` and will never set `@timeout` unless `locked?` returns true.
To work around the issue had to do this in initializer code and skip using `timeout=`:
``` ruby
module ResqueSchedulerLockingWithShorterTimeout
  def master_lock
    if @master_lock.nil?
      super
      @master_lock.instance_variable_set("@timeout", 30)
    end
    @master_lock
  end
end
Resque::Scheduler::Locking.prepend(ResqueSchedulerLockingWithShorterTimeout)
module Resque::Scheduler
  private

  extend Resque::Scheduler::Locking
end
```
