### ISSUE TITLE
Cannot load multiple files

### ISSUE THREAD

**Issue by bputek** [resque/resque-scheduler#465]
When I try and load a second file into the scheduler it removes all of the entries from the first file.  There are no overlaps in the keys being loaded in.  I feel like this should work, so am I missing something?

-B

**Comment by yaauie** [comment]
Each schedule file is its own schedule; loading one sets it as *the* canonical schedule, removing all old schedule entries, just as you're experiencing.

This is either by design, or has been the way things work for so long that to make it work any other way would break expectations.

If you feel the docs aren't clear enough, we'd gladly accept a pull-request that helps add clarity :)
