### ISSUE TITLE
The resque-web Schedule tab has old/different data for each unicorn worker

### ISSUE THREAD

**Issue by nroose** [resque/resque-scheduler#482]
This stuff is great! But I have one problem, which is that the Schedule tab on the resque web console seems to change between a few different sets if data, seemingly different snapshots in time.  And if I restart the unicorns, it stays the same.  This does not happen for the Overview or other tabs.  Any help would be greatly appreciated.

**Comment by nroose** [comment]
This is true on both the old sinatra resque web interface, as well as on the rails based resque-web and resque-scheduler-web interface

**Comment by carsonreinke** [comment]
@nroose are you still seeing this issue?

**Comment by nroose** [comment]
I no longer work at the place where was seeing this. Sorry

**Comment by yevgeniypopov** [comment]
I have the same issue with resque-scheduler 4.2.1, rails and unicorn. I guess it happens because now resque-scheduler stores non persistent schedules in memory instead of Redis DB. So when you make some dynamic changes to the schedule, only one unicorn worker will see them. 

Workaround: add 'persist' configuration to a schedule so all unicorn workers will read data from the same source(Redis DB).

**Comment by carsonreinke** [comment]
Not using a `persist` schedule is like a static schedule that is dynamically set similar to how `schedule=` is set.  It is confusing.
