### ISSUE TITLE
Issue with two workers

### ISSUE THREAD

**Issue by gogainda** [resque/resque-scheduler#485]
I have a staging sever with following settings:
There are 2 apps and 1 redis. For the app#1 there is a resque  environment  worker#1(*=>1). For the app#2 I have added environment worker#2(*=>1). When I add a job in app#2, job execution sometimes fails with name error (constant is not defined). Seems that some jobs from app#2 are being executed in app#1 environment. How can I fix this?

**Comment by lukeasrodgers** [comment]
I've never tried this particular setup you're using, but I'd recommend using different redis databases. Redis comes with 16 dbs per server, indexed from 0 to 15 IIRC, so I'd just use different redis dbs for each app's resque integration.

**Comment by will3216** [comment]
In addition, if you setup the jobs so that they are placed on separate queues, eg. :app_1_queue and :app_2_queue. Then start the workers so that they are only reading from their respective queues, this should also solve the issue.

**Comment by carsonreinke** [comment]
resque-scheduler just uses the configuration from `Resque.redis`, if you had setup two separate Rake tasks with different Redis configurations (like a different Redis DB number), you could run multiple schedulers.  Don't put any of this in a Rails initializer, unless you are have something to deviate the configuration (like an environment variable).  Setting up resque-web might be little difficult though.

If you can provide the exact error, that would help look into this closely.  Otherwise I am going to close this.
