### ISSUE TITLE
resque-web basic auth doesn't work

### ISSUE THREAD

**Issue by triptec** [resque/resque-scheduler#489]
Seems like setting RESQUE_WEB_HTTP_BASIC_AUTH_USER and RESQUE_WEB_HTTP_BASIC_AUTH_PASSWORD doesn't work to get basic auth.

Or is this only me?

**Comment by yaauie** [comment]
The `resque-scheduler` project does not provide this functionality; please reopen your bug against the [`resque-web`](https://www.github.com/resque/resque-web) project.

**Comment by jtmarmon** [comment]
for anyone else who ran into this issue, this happened to me because I followed advice in #301 which says to use the direct sinatra server like so:

```rb
mount Resque::Server.new, :at => '/resque'
```

The problem is that this loses you basic auth (and probably other features) from resque web. My solution was to go with @mattgibson's implementation which can be found here: https://github.com/mattgibson/resque-scheduler-web

Instructions on installing: https://github.com/resque/resque-scheduler/issues/301#issuecomment-97022567
